### ISSUE TITLE
Remove explore endpoint

### ISSUE THREAD

**Issue by samuveth** [snapshot-labs/snapshot#1437]
#### Main page
- Search
- Filtering by category & network
- Space ordering
- Number of spaces

#### Space page
- Number of members
- Name and image
- Proposals count 

#### Delegation page
- Space key validation
- Network

#### Custom domains
- Skin

#### HUB
- [ ] Move ordering logic to the hub https://github.com/snapshot-labs/snapshot-hub/issues/226
- [ ] Add query for loading spaces by a search string https://github.com/snapshot-labs/snapshot-hub/issues/227
- [ ] Add query for loading spaces by category and network https://github.com/snapshot-labs/snapshot-hub/issues/228
- [ ] Add total number of spaces to the spaces query https://github.com/snapshot-labs/snapshot-hub/issues/199
- [x] Add total number of proposals to space query https://github.com/snapshot-labs/snapshot-hub/issues/238
- [x] Add queries for plugins, validations, strategies, networks, skins
- [x] Add followersCount to space query

#### Frontend
- [x] Change how space loads initially https://github.com/snapshot-labs/snapshot/pull/1457
  - [x] #1458
- [x] #1467
- [x] Add query for space skin  (only on custom domain) https://github.com/snapshot-labs/snapshot/pull/1442
- [x] #1498

**Comment by zzuziak** [comment]
Hey @samuveth! What's the status of this issue? I can see multiple PRs open, are they still relevant?

**Comment by samuveth** [comment]
@zzuziak the status is that no one cares about making Snapshot.org great. Everything is about SX these days.

**Comment by samuveth** [comment]
I only see open issues.

**Comment by samuveth** [comment]
Yes, it's still relevant but they are all HUB related issues and it's nearly impossible to get stuff done on the HUB. Why you need to ask @bonustrack

**Comment by ChaituVR** [comment]
Updated todo:
- [ ] [hub] New endpoint to get metrics like total spaces, networks, strategies, and plugins
- [ ] [UI] Use new endpoint for metrics
- [ ] [hub] `space` query to return data using `orderBy` with `rank` by default
    - [ ] [hub] Use logic from [here](https://github.com/snapshot-labs/snapshot/blob/develop/src/composables/useSpaces.ts#L61-L89) to rank space 
- [ ] [hub] `space` query should accept the `category` filter into the `where` clause
- [ ] [hub] `space` query should accept the `network` filter into the `where` clause
- [ ] [hub] `space` query should accept the `id_contains` filter into `where` similar to `strategies_contains` in the `proposal` query
- [ ] [UI] Replace explore endpoint with `space` query.
    - [ ] [UI] Make sure the pagination is working well, with network and category filters
- [ ] [hub] Remove explore endpoint

Future todo:
- [ ] Add the total number of spaces to the spaces query https://github.com/snapshot-labs/snapshot-hub/issues/199
- [ ] Add queries for strategies, validations, plugins, and networks so UI will always use graphql

**Comment by samuveth** [comment]
@ChaituVR has there been any progress on this?
