### ISSUE TITLE
Manage email subscription from user profile

### ISSUE THREAD

**Issue by wa0x6e** [snapshot-labs/snapshot#3886]
### Issues

Allow users to manage their email preferences directly from snapshot UI

### Changes 

This will be a new modal, containing a form with the email notifications settings.

If user is not subscribed yet, the 'SUBSCRIBE' link from the header dropdown menu will open a modal with the subscription form (implemented via https://github.com/snapshot-labs/snapshot/pull/3754)
If user is already subscribed, the modal will show the management subscription form

Modal will looks like: 

----------------------------------------
Email subscriptions                  [x]
----------------------------------------

[] Proposal creation (<- checkbox)
[] Proposal closing
[] Weekly report

Select all | Unselect all (<- js event to select all checkboxes)

[UPDATE SUBSCRIPTION] (<- submit button)

----------------------------------------

On submit, we will ask the user to sign a message to prove he's the wallet owner.

### How to test

1. Log in to your account
2. Open account dropdown menu in header
3. Click on 'Subscribe'
4. In the modal, edit the form 
5. Submit the form
6. Sign the message
7. See error/success message

### To-Do

- [ ] Show the form in relevant places 
- [ ] Add modal/message when subscription is successful
- [ ] Add error message on error

### Self-review checklist
- [ ] I have performed a full self-review of my changes
- [ ] I have tested my changes on a preview deployment
- [ ] I have tested my changes on a custom domain
- [ ] I have run end-to-end tests `yarn cypress:test:e2e`, and they have passed

### Todo 

Since we're now opening 2 different modals with the same link, maybe we should rename this menu 'Email notifications'

**Comment by samuveth** [comment]
Are the settings saved on the user profile or on envelope?

**Comment by samuveth** [comment]
@Todmy, I noticed that the designs for subscription management haven't been included in the project pitch. Could you please provide some initial design or wireframes for us to review and agree upon before we proceed with the coding implementation?

**Comment by wa0x6e** [comment]
User subscriptions are stored with envelop.
List of different subscriptions options are stored on envelop.

Both data can be retrieved with an api request to envelop.

There will be a rest api to update the subscriptions.

**Comment by wa0x6e** [comment]
First post has been updated with the new specs

**Comment by Todmy** [comment]
@samuveth what do you think about this?:


![Image](https://github.com/snapshot-labs/snapshot/assets/7693369/7844e2a1-2cdc-4db2-9f71-b7a0e3af187f)

Let's start with this, and we can decide how it will look.

**Comment by wa0x6e** [comment]
- Check all should be a link

**Comment by bonustrack** [comment]
We should always use "Sentence case" not "Title Case"

**Comment by wa0x6e** [comment]
maybe also add "Uncheck all"

**Comment by samuveth** [comment]
Yes, these are our checkboxes although the design for them isn't set in stone yet. We could alternative use `TuneSwitch` component instead of `TuneCheckbox` 
<img width="414" alt="image" src="https://github.com/snapshot-labs/snapshot/assets/51686767/222db96f-683d-4548-abbb-41499a327e1f">

We don't need "Uncheck all" in this case

**Comment by Todmy** [comment]
![Image](https://github.com/snapshot-labs/snapshot/assets/7693369/af71169a-c3b9-49cf-ae09-15a9af658bb6)

I have tried to consider all your ideas. What do you think?

**Comment by wa0x6e** [comment]
@samuveth Why do you think we don't need the check/uncheck all ?

**Comment by samuveth** [comment]
We should consider incorporating a dynamic button, as suggested in your design found here: https://github.com/snapshot-labs/envelop/pull/55#issuecomment-1544511596

This button's functionality would depend on the current state of the items. If more than one item is selected, the button should display "Uncheck All". And if less than two items are selected, the button should change to "Check All". WDYT?

**Comment by samuveth** [comment]
@Todmy can you also add the sub text from the design I linked about?

"Selected the email categories you wish to receive:"

And also the sub text for each item too

**Comment by Todmy** [comment]
Updated

![Image](https://github.com/snapshot-labs/snapshot/assets/7693369/d088db3a-d03a-4607-a3ea-6f57720252ef)

**Comment by wa0x6e** [comment]
If putting the check all button at this place, it should be a submit button, and the label should reflect that by saying "Subscribe to all".

If it's purpose if just to check the checkboxes, without submitting the form, it should not look like a submit button

**Comment by Todmy** [comment]
![Image](https://github.com/snapshot-labs/snapshot/assets/7693369/f03eba36-bba6-4776-bda7-c654f0527bef)

I have updated the second button text.

Also, I would like to know how you want it to behave. When half or more than half of selected, then it should allow you to subscribe to all types of email, otherwise it will unsubscribe the user from all types of subscriptions. Does it correct?

**Comment by wa0x6e** [comment]
That second button is still bothering me. I think we should just remove it altogether.

It's bad UX to have a submit button do different thing, depending on what is checked.

Either we have
- Uncheck all | check all (simple link, above the blue submit button)
- No second button nor links, just the blue one for update

Reproducing the second button from https://github.com/snapshot-labs/envelop/pull/55#issuecomment-1544511596 is not ideal, as the page is targeted toward user who already wants to unsubscribe, the page was introduced to try to retain them as last resort.

We should not have a button to facilitate unsubscription from snapshot side, because the emails are removed from DB, and they will be required to subscribe and verify email again. (if user can reactivate emails without all the hassle, it will be a different story).

**Comment by wa0x6e** [comment]
I was thinking something like that
![Screenshot 2023-05-15 at 3 27 35 PM](https://github.com/snapshot-labs/snapshot/assets/495709/0d96ee29-a79d-4746-9cbe-869dfd66f278)

Let's just agree to remove it altogether, all of the site I've tested does not have this button anymore, and it makes sense only on an unsubscribe page, and not manage preferences page.

**Comment by samuveth** [comment]
I think we should remove the "un/subscribe to all" button. we can handle unsubscriptions from the unsubscribe link in the email.

**Comment by Todmy** [comment]
here is an improvement added to the task. We need to add an ability for a client to remove email from DB completely. This is the draft of design:

![Image](https://github.com/snapshot-labs/snapshot/assets/7693369/63334746-28aa-470a-889c-48ba381b1b7e)

this checkbox appears only if all switches are turned off.

**Comment by aurelianoB** [comment]
I can live with this design for now. Probably worth revisiting once we have a designer. As for the text in the last checkbox, maybe we could just make it a one liner by saying "Remove my email from Snapshot's database".

@samuveth might come up with better text though.

**Comment by Todmy** [comment]
updated

![Image](https://github.com/snapshot-labs/snapshot/assets/7693369/9ee9d37a-2432-4846-89dd-223e4dc5f54b)

**Comment by aurelianoB** [comment]
Nit, but note that checkbox will only show if all toggles are switched off

**Comment by Todmy** [comment]
@aurelianoB Yes, definitely.
