### ISSUE TITLE
Reusable setup form

### ISSUE THREAD

**Issue by j0hnfl0w** [snapshot-labs/snapshot#3889]
```[tasklist]
### Tasks
- [ ] Add setup form to space settings
- [ ] Setup form should be disabled if already setup
- [ ] Only space owner can edit the form
```
