### ISSUE TITLE
NFT section in user profile

### ISSUE THREAD

**Issue by j0hnfl0w** [snapshot-labs/snapshot#3891]
```[tasklist]
### Tasks
- [ ] Show a list of X latest minted  NFTS
- [ ] Add a more button, to open the view more modal
- [ ] View more modal: show full list of minted NFTs, use same layout as NFT explorer
```
