### ISSUE TITLE
Limit the upload of large files and different extensions

### ISSUE THREAD

**Issue by ChaituVR** [snapshot-labs/snapshot#4109]
```[tasklist]
### Tasks
- [x] Display error if the file size is more than 1MB
- [x] Only allow file extensions `.jpg`, `.jpeg`, `.png`, and `.gif`
- [ ] ~~[Optional] Show error if user tries to upload image with width/height greater than `1000px`~~
- [x] [Optional] Display human-readable error in case an error is returned from pineapple (may depend on https://github.com/snapshot-labs/pineapple/issues/140)
```
