### ISSUE TITLE
[NEW FEATURE] - Add support for optimistic quorum 

### ISSUE THREAD

**Issue by ChaituVR** [snapshot-labs/snapshot#4600]
### Briefly describe the feature.

Add support for optimistic quorum

### Which problem is this feature trying to solve?

We should add an option for quorum rejection, In which by default proposal are approved unless there is a quorum of reject

### What is the expected solution?

 New option in settings to store quorum type (quorum_type = default to 'normal')
- Space admins can change it to 'optimistic'
- In 'normal' mode, we consider all voting power of all choices (current approach) 
- In 'optimistic' mode, we consider only the voting power of the choice 2 (which is mostly no or against or reject)
- [UI] Proposal page, if proposal has optimistic quorum 
    - ![image](https://github.com/snapshot-labs/snapshot/assets/15967809/d02ee701-eb65-466a-ae76-d456760eb38c)
    - Show a ✅ on quorum if the choice 2 has less than quorum value
    - Show a ❌ on quorum if the choice 2 has more than quorum value
- [UI] Proposals page, if proposal has optimistic quorum 
    - ![image](https://github.com/snapshot-labs/snapshot/assets/15967809/b8d06da1-da2a-41bd-95e2-8f1b2c641dd7) 
    - If quorum rejection is reached, display a message like "112% quorum reached to reject" 
    - If quorum reject is not reached, display a message like "Quorum not reached to reject"
- Update docs

```[tasklist]
### Tasks
- [ ] https://github.com/snapshot-labs/snapshot.js/pull/974
- [ ] https://github.com/snapshot-labs/snapshot-sequencer/pull/315
- [ ] https://github.com/snapshot-labs/snapshot-hub/pull/827
- [ ] https://github.com/snapshot-labs/snapshot/pull/4625
- [ ] https://github.com/snapshot-labs/snapshot/pull/4626
- [ ] Rename to "Quorum of rejection" https://github.com/snapshot-labs/snapshot/pull/4677
- [ ] [Docs] Add how quorum and quorum of rejection works
```

**Comment by samuveth** [comment]
This should only be enabled for Basic voting voting proposals I think? @ChaituVR

**Comment by ChaituVR** [comment]
> This should only be enabled for Basic voting voting proposals I think? @ChaituVR

Yes, but after looking at proposals like this https://snapshot.org/#/safe.eth/proposal/0x1d65ca5270b4aa1efaa7b7ca4e17976a99b802efcf678ac2909eb836b1662a29
I thought we could leave it on all voting types but we should have good docs that suggest that it ignores second option

**Comment by ChaituVR** [comment]
Also i already have some changes in my local 😅
