### ISSUE TITLE
Move testnet.snapshot.org to sepolia

### ISSUE THREAD

**Issue by ChaituVR** [snapshot-labs/snapshot#4614]
```[tasklist]
### Tasks
- [ ] https://github.com/snapshot-labs/snapshot.js/issues/978
- [x] Support Safe voting on sepolia safe,, remove support for goerli on relayer https://github.com/snapshot-labs/snapshot-relayer/pull/215
- [ ] https://github.com/snapshot-labs/snapshot.js/pull/980
- [x] Make sure demo UI is working with sepolia  https://github.com/snapshot-labs/snapshot/pull/4622
- [x] Check if we are able to create spaces/update space settings with Sepolia's ENS names
- [x] Announce about DB reset and goerli deprecation
- [x] [After announcement] Just before announced time, make sure maintainance is enabled on testnet.snapshot.org
- [x] [After announcement] Backup existing testnet hub DB and testnet sequencer DB
- [x] [After announcement] DB reset for snapshot-testnet and snapshot-sequencer-testnet
- [x] [After announcement] Update env in testnet UI and sequencer
- [ ] https://github.com/snapshot-labs/snapshot.js/issues/985
```

**Comment by samuveth** [comment]
@ChaituVR shouldn't we announce the DB reset asap?
